### ISSUE TITLE
Timeout on some cards

### ISSUE THREAD

**Issue by Haniek** [schmich/hearthstone-card-images#3]
Hi,

Some images are timing out during the request. An example would be https://cdn.rawgit.com/schmich/hearthstone-card-images/f5d6/rel/OG_311.png .
Is this a known issue / temporary issue?

Thanks in advance.

**Comment by schmich** [comment]
It's a temporary issue.

This projects uses [RawGit](http://rawgit.com/) (which in turn uses [StackPath](https://stackpath.com/)) as a CDN. Unfortunately, because these services are being offered for free, there are no uptime guarantees. RawGit appeared to be down earlier, which would explain the outage. I don't have availability numbers for you, but outages have been rare.

You can mitigate RawGit/StackPath outages by caching the images on your own servers or in your app/site. Otherwise, unless there is a more generous offer for a free CDN with guaranteed availability, this is the best I can do with the resources I have available.
